version: "3.3"

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.docker/config.json:/config.json
    command: --label-enable --cleanup --schedule "0 0 11 * * *"
    restart: unless-stopped
    
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    networks:
      default:
        ipv4_address: 172.20.1.2
    ports:
      - 8989:8989
    depends_on:
      - jackett
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.sonarr.rule=Host(`sonarr.${DOMAIN}`)
      - traefik.http.routers.sonarr.entrypoints=websecured
      - traefik.http.routers.sonarr.tls.certresolver=myresolver
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONTAINERS}/sonarr/config:/config
      - ${CONTAINERS}/sonarr/empty:/downloads # Not used
      - ${DATA}:/data
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    networks:
      default:
        ipv4_address: 172.20.1.3
    ports:
      - 7878:7878
    depends_on:
      - jackett
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.radarr.rule=Host(`radarr.${DOMAIN}`)
      - traefik.http.routers.radarr.entrypoints=websecured
      - traefik.http.routers.radarr.tls.certresolver=myresolver
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONTAINERS}/radarr/config:/config
      - ${CONTAINERS}/radarr/empty:/downloads # Not used
      - ${DATA}:/data
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    networks:
      default:
        ipv4_address: 172.20.1.4
    ports:
      - 6767:6767
    depends_on:
      - sonarr
      - radarr
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.bazarr.rule=Host(`bazarr.${DOMAIN}`)
      - traefik.http.routers.bazarr.entrypoints=websecured
      - traefik.http.routers.bazarr.tls.certresolver=myresolver
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONTAINERS}/bazarr/config:/config
      - ${DATA}:/data
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    networks:
      default:
        ipv4_address: 172.20.1.5
    ports:
      - 9117:9117
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.jackett.rule=Host(`jackett.${DOMAIN}`)
      - traefik.http.routers.jackett.entrypoints=websecured
      - traefik.http.routers.jackett.tls.certresolver=myresolver
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - AUTO_UPDATE=true
    volumes:
      - ${CONTAINERS}/jackett/config:/config
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    networks:
      default:
        ipv4_address: 172.20.2.2
    ports:
      - 9000:9000
      - 8000:8000
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN}`)
      - traefik.http.routers.portainer.entrypoints=websecured
      - traefik.http.routers.portainer.tls.certresolver=myresolver
      - traefik.http.services.portainer.loadbalancer.server.port=9000
    restart: always
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONTAINERS}/portainer:/data

  portainer_agent:
    image: portainer/agent
    container_name: portainer-agent
    networks:
      default:
        ipv4_address: 172.20.2.3
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=false

  organizr:
    image: organizr/organizr
    container_name: organizr
    networks:
      default:
        ipv4_address: 172.20.2.4
    ports:
      - 9983:80
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.orzanizr.rule=Host(`organizr.${DOMAIN}`) || Host(`mediabox.${DOMAIN}`)
      - traefik.http.routers.orzanizr.entrypoints=websecured
      - traefik.http.routers.orzanizr.tls.certresolver=myresolver
      - traefik.http.services.organizr.loadbalancer.server.port=80
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONTAINERS}/organizr:/config
    restart: unless-stopped
    
    jellyfin:
        image: jellyfin/jellyfin
        container_name: jellyfin
        networks:
          default:
            ipv4_address: 172.20.2.124
        ports:
          - 8096:8096
        labels:
          - com.centurylinklabs.watchtower.enable=true
          - traefik.enable=false
        network_mode: "host"
        environment:
          - PUID=${PUID}
          - PGID=${PGID}
          - TZ=${TIMEZONE}
        volumes:
          - ${CONTAINERS}/jellyfin/config:/config
          - ${CONTAINERS}/jellyfin/cache:/cache
          - ${CONTAINERS}/jellyfin/media:/media
          - ${CONTAINERS}/jellyfin/media2:/media2:ro
        restart: "unless-stopped"
        
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
